### PR TITLE
Make `capitalized-comments` rule ignore webpack magic comments

### LINKED ISSUE #62: `capitalized-comments` ignore webpack magic comments
```js
import(
  /* webpackChunkName: "my-chunk-name" */ './some-chunk' // Error: Comments should not begin with a lowercase character
);
```
https://webpack.js.org/api/module-methods/#magic-comments

### PR DESCRIPTION
**Pull request by yangmingshan**
Fix #62

### CODE REVIEW

**Comment by sindresorhus** [comment]
What other magic Webpack comments are there? If none, then I would be more specific in the regex.

**Comment by yangmingshan** [comment]
All webpack magic comments starts with `webpack`, so I just add `webpack`.

- webpackInclude
- webpackExclude
- webpackChunkName
- webpackMode
- webpackPrefetch
- webpackPreload
- webpackIgnore

File: index.js [hunk 1]
```diff
@@ -247,7 +247,7 @@ module.exports = {
 			'always',
 			{
 				// You can also ignore this rule by wrapping the first word in quotes.
-				ignorePattern: /pragma|ignore|prettier-ignore/.source,
+				ignorePattern: /pragma|ignore|prettier-ignore|webpack/.source,
```
Comment (sindresorhus) [inline index.js:250]:
```suggestion
				ignorePattern: /pragma|ignore|prettier-ignore|webpack\w+:/.source,
```

I assume all the magic comments end in `:`?

I just want to ensure that comment like:

```js
// webpack does not like this
```

are caught.
